.TH "DistPareto" 3 "20 Jun 2001" "LDSequences" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DistPareto \- This class describes the Pareto distribution. 
.SH SYNOPSIS
.br
.PP
\fC#include <Distributions.h>\fP
.PP
Inherits \fBDistribution\fP.
.PP
Inherited by \fBDistPareto0\fP.
.PP
.SS "Public Methods"

.in +1c
.ti -1c
.RI "\fBDistPareto\fP (Zahl aa=1, Zahl bb=1)"
.br
.ti -1c
.RI "virtual \fB~DistPareto\fP ()"
.br
.ti -1c
.RI "virtual string \fBDistributionName\fP ()"
.br
.ti -1c
.RI "virtual Zahl \fBpdf\fP (Zahl y, Zahl para, Zahl para1)"
.br
.ti -1c
.RI "virtual Zahl \fBTransform\fP (Zahl y, Zahl aa, Zahl bb)"
.br
.ti -1c
.RI "virtual Zahl \fBcdf\fP (Zahl y, Zahl para, Zahl para1)"
.br
.ti -1c
.RI "virtual Zahl \fBcdfc\fP (Zahl y, Zahl para, Zahl para1)"
.br
.ti -1c
.RI "virtual int \fBRange\fP ()"
.br
.ti -1c
.RI "virtual int \fBParameterRange\fP (int paranr)"
.br
.ti -1c
.RI "virtual Zahl \fBmgf\fP (Zahl y, Zahl para, Zahl para1)"
.br
.ti -1c
.RI "virtual Zahl \fBMoment\fP (int k, Zahl para, Zahl para1)"
.br
.ti -1c
.RI "virtual Zahl \fBMean\fP (Zahl para, Zahl para1)"
.br
.ti -1c
.RI "virtual Zahl \fBVariance\fP (Zahl para, Zahl para1)"
.br
.ti -1c
.RI "virtual Zahl \fBSkewness\fP (Zahl para, Zahl para1)"
.br
.ti -1c
.RI "virtual Zahl \fBKurtosis\fP (Zahl para, Zahl para1)"
.br
.ti -1c
.RI "virtual Zahl \fBLogLikelihood\fP (Zahl y, Zahl para, Zahl para1)"
.br
.ti -1c
.RI "virtual Zahl \fBCharacteristicFunction\fP (Zahl y, Zahl para, Zahl para1)"
.br
.ti -1c
.RI "virtual Zahl \fBMedian\fP (Zahl para, Zahl para1)"
.br
.ti -1c
.RI "virtual Zahl \fBQ1\fP (Zahl para, Zahl para1)"
.br
.ti -1c
.RI "virtual Zahl \fBQ3\fP (Zahl para, Zahl para1)"
.br
.ti -1c
.RI "virtual Zahl \fBMode\fP (Zahl para, Zahl para1)"
.br
.ti -1c
.RI "virtual Zahl \fBqMean\fP (Zahl para, Zahl para1)"
.br
.ti -1c
.RI "virtual Zahl \fBqMode\fP (Zahl para, Zahl para1)"
.br
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
This class describes the Pareto distribution.
.PP
\fBAuthor(s): \fP
.in +1c
Reinhold Kainhofer 
.PP
.SH "CONSTRUCTOR & DESTRUCTOR DOCUMENTATION"
.PP 
.SS "DistPareto::DistPareto (Zahl aa = 1, Zahl bb = 1)"
.PP
.SS "DistPareto::~DistPareto ()\fC [virtual]\fP"
.PP
.SH "MEMBER FUNCTION DOCUMENTATION"
.PP 
.SS "Zahl DistPareto::CharacteristicFunction (Zahl y, Zahl para, Zahl para1)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "string DistPareto::DistributionName ()\fC [virtual]\fP"
.PP
Returns a string specifying the name of this distribution.
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "Zahl DistPareto::Kurtosis (Zahl para, Zahl para1)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "Zahl DistPareto::LogLikelihood (Zahl y, Zahl para, Zahl para1)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "Zahl DistPareto::Mean (Zahl para, Zahl para1)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "Zahl DistPareto::Median (Zahl para, Zahl para1)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "Zahl DistPareto::Mode (Zahl para, Zahl para1)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "Zahl DistPareto::Moment (int k, Zahl para, Zahl para1)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "int DistPareto::ParameterRange (int paranr)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.SS "Zahl DistPareto::Q1 (Zahl para, Zahl para1)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "Zahl DistPareto::Q3 (Zahl para, Zahl para1)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "int DistPareto::Range ()\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "Zahl DistPareto::Skewness (Zahl para, Zahl para1)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "Zahl DistPareto::Transform (Zahl y, Zahl aa, Zahl bb)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "Zahl DistPareto::Variance (Zahl para, Zahl para1)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "Zahl DistPareto::cdf (Zahl y, Zahl para, Zahl para1)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "Zahl DistPareto::cdfc (Zahl y, Zahl para, Zahl para1)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "Zahl DistPareto::mgf (Zahl y, Zahl para, Zahl para1)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "Zahl DistPareto::pdf (Zahl y, Zahl para, Zahl para1)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "Zahl DistPareto::qMean (Zahl para, Zahl para1)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.
.SS "Zahl DistPareto::qMode (Zahl para, Zahl para1)\fC [virtual]\fP"
.PP
Reimplemented from \fBDistribution\fP.
.PP
Reimplemented in \fBDistPareto0\fP.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for LDSequences from the source code.