.TH "matrix.h" 3 "20 Jun 2001" "LDSequences" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br
\fC#include 'BaseDefinitions.h'\fP
.br
.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBMatrix\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBmaxElem\fP   20"
.br
.ti -1c
.RI "#define \fBtrue\fP   1"
.br
.ti -1c
.RI "#define \fBfalse\fP   0"
.br
.ti -1c
.RI "#define \fBPi\fP   3.14159265358979323846264338328"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define Pi   3.14159265358979323846264338328"
.PP
.SS "#define false   0"
.PP
.SS "#define maxElem   20"
.PP
.SS "#define true   1"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for LDSequences from the source code.