.TH "matrix.cpp" 3 "20 Jun 2001" "LDSequences" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'matrix.h'\fP
.br
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBAbbruch\fP   1e-25"
.br
.ti -1c
.RI "#define \fBmaxRek\fP   100"
.br
.ti -1c
.RI "#define \fBLeftTop\fP   1"
.br
.ti -1c
.RI "#define \fBLT\fP   Lefttop"
.br
.ti -1c
.RI "#define \fBRightTop\fP   2"
.br
.ti -1c
.RI "#define \fBRT\fP   RightTop"
.br
.ti -1c
.RI "#define \fBLeftBottom\fP   3"
.br
.ti -1c
.RI "#define \fBLB\fP   LeftBottom"
.br
.ti -1c
.RI "#define \fBRightBottom\fP   4"
.br
.ti -1c
.RI "#define \fBRB\fP   RightBottom"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define Abbruch   1e-25"
.PP
.SS "#define LB   LeftBottom"
.PP
.SS "#define LT   Lefttop"
.PP
.SS "#define LeftBottom   3"
.PP
.SS "#define LeftTop   1"
.PP
.SS "#define RB   RightBottom"
.PP
.SS "#define RT   RightTop"
.PP
.SS "#define RightBottom   4"
.PP
.SS "#define RightTop   2"
.PP
.SS "#define maxRek   100"
.PP
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for LDSequences from the source code.