.TH "polynom" 3 "20 Jun 2001" "LDSequences" \" -*- nroff -*-
.ad l
.nh
.SH NAME
polynom \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SimSeqs.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdeg\fP"
.br
.ti -1c
.RI "\fBint_vektor\fP \fBcoeff\fP"
.br
.in -1c
.SH "MEMBER DATA DOCUMENTATION"
.PP 
.SS "\fBint_vektor\fP polynom::coeff"
.PP
.SS "int polynom::deg"
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for LDSequences from the source code.