foldersTree = gFld("<b>LDSequences</b>", "", "")
     insDoc(foldersTree, gLnk("Main Page", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("BaseDefinitions.cpp", "", "BaseDefinitions_8cpp.html"))
       insDoc(aux1, gLnk("BaseDefinitions.h", "", "BaseDefinitions_8h.html"))
       insDoc(aux1, gLnk("Distributions.cpp", "", "Distributions_8cpp.html"))
       insDoc(aux1, gLnk("Distributions.h", "", "Distributions_8h.html"))
       insDoc(aux1, gLnk("matrix.cpp", "", "matrix_8cpp.html"))
       insDoc(aux1, gLnk("matrix.h", "", "matrix_8h.html"))
       insDoc(aux1, gLnk("SimSeqs.cpp", "", "SimSeqs_8cpp.html"))
       insDoc(aux1, gLnk("SimSeqs.h", "", "SimSeqs_8h.html"))
aux1 = insFld(foldersTree, gFld("Compound List", "", "annotated.html"))
       insDoc(aux1, gLnk("DistBeta", "", "classDistBeta.html"))
       insDoc(aux1, gLnk("DistBradford", "", "classDistBradford.html"))
       insDoc(aux1, gLnk("DistCauchy", "", "classDistCauchy.html"))
       insDoc(aux1, gLnk("DistDiscrete", "", "classDistDiscrete.html"))
       insDoc(aux1, gLnk("DistExp", "", "classDistExp.html"))
       insDoc(aux1, gLnk("DistFoldedNormal", "", "classDistFoldedNormal.html"))
       insDoc(aux1, gLnk("DistGamma", "", "classDistGamma.html"))
       insDoc(aux1, gLnk("DistHalfNormal", "", "classDistHalfNormal.html"))
       insDoc(aux1, gLnk("DistLaplace", "", "classDistLaplace.html"))
       insDoc(aux1, gLnk("DistLogNormal", "", "classDistLogNormal.html"))
       insDoc(aux1, gLnk("DistNormal", "", "classDistNormal.html"))
       insDoc(aux1, gLnk("DistPareto", "", "classDistPareto.html"))
       insDoc(aux1, gLnk("DistPareto0", "", "classDistPareto0.html"))
       insDoc(aux1, gLnk("Distribution", "", "classDistribution.html"))
       insDoc(aux1, gLnk("DistTemplate", "", "classDistTemplate.html"))
       insDoc(aux1, gLnk("DistUniform", "", "classDistUniform.html"))
       insDoc(aux1, gLnk("DistWeibull", "", "classDistWeibull.html"))
       insDoc(aux1, gLnk("LDSqAfflerbach", "", "classLDSqAfflerbach.html"))
       insDoc(aux1, gLnk("LDSqAtanassov", "", "classLDSqAtanassov.html"))
       insDoc(aux1, gLnk("LDSqBase", "", "classLDSqBase.html"))
       insDoc(aux1, gLnk("LDSqFaure", "", "classLDSqFaure.html"))
       insDoc(aux1, gLnk("LDSqHalton", "", "classLDSqHalton.html"))
       insDoc(aux1, gLnk("LDSqHammersley", "", "classLDSqHammersley.html"))
       insDoc(aux1, gLnk("LDSqMonteCarlo", "", "classLDSqMonteCarlo.html"))
       insDoc(aux1, gLnk("LDSqNAlpha", "", "classLDSqNAlpha.html"))
       insDoc(aux1, gLnk("LDSqNetz", "", "classLDSqNetz.html"))
       insDoc(aux1, gLnk("LDSqNiederreiter", "", "classLDSqNiederreiter.html"))
       insDoc(aux1, gLnk("LDSqSobol", "", "classLDSqSobol.html"))
       insDoc(aux1, gLnk("longpoly", "", "classlongpoly.html"))
       insDoc(aux1, gLnk("Matrix", "", "classMatrix.html"))
       insDoc(aux1, gLnk("polynom", "", "structpolynom.html"))
aux1 = insFld(foldersTree, gFld("Class Hierarchy", "", "hierarchy.html"))
  aux2 = insFld(aux1, gFld("Distribution", "", "classDistribution.html"))
         insDoc(aux2, gLnk("DistBeta", "", "classDistBeta.html"))
         insDoc(aux2, gLnk("DistBradford", "", "classDistBradford.html"))
         insDoc(aux2, gLnk("DistCauchy", "", "classDistCauchy.html"))
         insDoc(aux2, gLnk("DistDiscrete", "", "classDistDiscrete.html"))
    aux3 = insFld(aux2, gFld("DistExp", "", "classDistExp.html"))
           insDoc(aux3, gLnk("DistLaplace", "", "classDistLaplace.html"))
         insDoc(aux2, gLnk("DistGamma", "", "classDistGamma.html"))
    aux3 = insFld(aux2, gFld("DistNormal", "", "classDistNormal.html"))
           insDoc(aux3, gLnk("DistFoldedNormal", "", "classDistFoldedNormal.html"))
           insDoc(aux3, gLnk("DistHalfNormal", "", "classDistHalfNormal.html"))
           insDoc(aux3, gLnk("DistLogNormal", "", "classDistLogNormal.html"))
    aux3 = insFld(aux2, gFld("DistPareto", "", "classDistPareto.html"))
           insDoc(aux3, gLnk("DistPareto0", "", "classDistPareto0.html"))
         insDoc(aux2, gLnk("DistTemplate", "", "classDistTemplate.html"))
         insDoc(aux2, gLnk("DistUniform", "", "classDistUniform.html"))
         insDoc(aux2, gLnk("DistWeibull", "", "classDistWeibull.html"))
  aux2 = insFld(aux1, gFld("LDSqBase", "", "classLDSqBase.html"))
         insDoc(aux2, gLnk("LDSqAtanassov", "", "classLDSqAtanassov.html"))
         insDoc(aux2, gLnk("LDSqFaure", "", "classLDSqFaure.html"))
    aux3 = insFld(aux2, gFld("LDSqHalton", "", "classLDSqHalton.html"))
           insDoc(aux3, gLnk("LDSqHammersley", "", "classLDSqHammersley.html"))
    aux3 = insFld(aux2, gFld("LDSqMonteCarlo", "", "classLDSqMonteCarlo.html"))
           insDoc(aux3, gLnk("LDSqAfflerbach", "", "classLDSqAfflerbach.html"))
         insDoc(aux2, gLnk("LDSqNAlpha", "", "classLDSqNAlpha.html"))
         insDoc(aux2, gLnk("LDSqNetz", "", "classLDSqNetz.html"))
         insDoc(aux2, gLnk("LDSqNiederreiter", "", "classLDSqNiederreiter.html"))
         insDoc(aux2, gLnk("LDSqSobol", "", "classLDSqSobol.html"))
       insDoc(aux1, gLnk("longpoly", "", "classlongpoly.html"))
       insDoc(aux1, gLnk("Matrix", "", "classMatrix.html"))
       insDoc(aux1, gLnk("polynom", "", "structpolynom.html"))
     insDoc(foldersTree, gLnk("Compound Members", "", "functions.html"))
     insDoc(foldersTree, gLnk("File Members", "", "globals.html"))
     insDoc(foldersTree, gLnk("Graphical Class Hierarchy", "", "inherits.html"))
