#!/bin/sh
clear
echo "Starting at `date`"

go=8
BIN="/home/bienvenue/Documents/DFPT+U/dfptu_git_03.07.2016/bin"
RUN="mpirun $BIN/pw.x -np $go "
NAME="res-k.dat"

echo "k energy" > $NAME
ecutrho=160
ecut=27

rm outputs/* inputs/* 2>/dev/null

for k in `seq 2 2 16`
do

rm -r tmp/ 2>/dev/null

# self-consistent calculation
cat > inputs/si.scf.ultra.$k.in << EOF
 &control
    pseudo_dir = '.',
    outdir='./tmp/',
    verbosity = 'high',
    tstress = .true.
    tprnfor = .true.
    prefix='si',
 /
 &system
    ibrav=  2, celldm(1)=10.2612, nat=  2, ntyp= 1,
    ecutwfc = $ecut
    ecutrho = $ecutrho
 /
 &electrons
    mixing_beta = 0.7 
    mixing_mode = 'plain',
    conv_thr =  1.0d-9,
 /
ATOMIC_SPECIES
 Si  28.086  Si.pbesol-n-rrkjus_psl.1.0.0.UPF
ATOMIC_POSITIONS crystal
 Si 0.1   0.0   0.0 
 Si 0.25  0.25  0.25 
K_POINTS automatic
$k $k $k 0 0 0
EOF

$RUN < inputs/si.scf.ultra.$k.in > outputs/si.scf.ultra.$k.out

energy=`grep "!    total energy" outputs/si.scf.ultra.$k.out | awk '{print $5}'`
totforce=`grep "Total force" outputs/si.scf.ultra.$k.out | awk '{print $4}'`
presure=`grep "P=" outputs/si.scf.ultra.$k.out | awk '{print $6}'`
echo "$k $totforce $presure $energy" >> $NAME
echo "$k $totforce $presure $energy"


done

echo "Finishing at `date`"
