# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_sobol', [dirname(__file__)])
        except ImportError:
            import _sobol
            return _sobol
        if fp is not None:
            try:
                _mod = imp.load_module('_sobol', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _sobol = swig_import_helper()
    del swig_import_helper
else:
    import _sobol
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _sobol.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _sobol.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _sobol.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _sobol.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _sobol.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _sobol.SwigPyIterator_equal(self, x)

    def copy(self):
        return _sobol.SwigPyIterator_copy(self)

    def next(self):
        return _sobol.SwigPyIterator_next(self)

    def __next__(self):
        return _sobol.SwigPyIterator___next__(self)

    def previous(self):
        return _sobol.SwigPyIterator_previous(self)

    def advance(self, n):
        return _sobol.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _sobol.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _sobol.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _sobol.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _sobol.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _sobol.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _sobol.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _sobol.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)


def seb(spatialDIM, Npoints, avoid):
    return _sobol.seb(spatialDIM, Npoints, avoid)
seb = _sobol.seb

def sobol(argc, argv):
    return _sobol.sobol(argc, argv)
sobol = _sobol.sobol

def i8_bit_hi1(n):
    return _sobol.i8_bit_hi1(n)
i8_bit_hi1 = _sobol.i8_bit_hi1

def i8_bit_lo0(n):
    return _sobol.i8_bit_lo0(n)
i8_bit_lo0 = _sobol.i8_bit_lo0

def i8_sobol(dim_num, seed, quasi):
    return _sobol.i8_sobol(dim_num, seed, quasi)
i8_sobol = _sobol.i8_sobol

def i8_sobol_generate(m, n, skip):
    return _sobol.i8_sobol_generate(m, n, skip)
i8_sobol_generate = _sobol.i8_sobol_generate

def r8mat_write(output_filename, m, n, table):
    return _sobol.r8mat_write(output_filename, m, n, table)
r8mat_write = _sobol.r8mat_write

def timestamp():
    return _sobol.timestamp()
timestamp = _sobol.timestamp

def maxiReturn(m, skip):
    return _sobol.maxiReturn(m, skip)
maxiReturn = _sobol.maxiReturn

def emergency(m, seed, place):
    return _sobol.emergency(m, seed, place)
emergency = _sobol.emergency
# This file is compatible with both classic and new-style classes.


